blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://steampipe.io/community/join
    about: Please ask any questions in our Slack channel.
  - name: Steampipe CLI Bug Reports and Feature Requests
    url: https://github.com/turbot/steampipe/issues/new/choose
    about: Steampipe CLI has its own codebase. Bug reports and feature requests for those pieces of functionality should be directed to that repository.
